name: vite
description: A dart library for the Vite blockchain. Send transactions and interact with smart contracts!
homepage: https://viterium.io
repository: https://github.com/viterium/vite_dart
version: 0.1.1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bip39: ^1.0.6
  decimal: ^2.1.0
  freezed_annotation: ^1.1.0
  hex: ^0.2.0
  http: ^0.13.3
  json_annotation: ^4.4.0
  json_converter: ^2.0.0
  json_rpc_2: ^3.0.1
  pointycastle: ^3.5.2
  stream_channel: ^2.1.0
  string_validator: ^0.3.0
  typed_data: ^1.3.0
  web_socket_channel: ^2.1.0

dev_dependencies:
  build_runner: ^2.1.8
  freezed: ^1.1.1
  json_serializable: ^6.1.5
  lints: ^1.0.1
  test: ^1.20.2

scripts:
  codegen: dart run build_runner build --delete-conflicting-outputs
